#!/usr/bin/env bash

paru -Syu
paru -S --noconfirm --needed rofi-wayland clang waybar otf-font-awesome hyprpaper neovim btop zsh hyprshot librewolf ttf-adwaita-mono-nerd mesa xf86-video-amdgpu vulkan-radeon noto-fonts noto-fonts-cjk noto-fonts-emoji nordvpn pavucontrol blueman fzf

hash -r
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
