#!/usr/bin/env bash

sudo pacman -Syu
sudo pacman -S --noconfirm --needed rofi-wayland clang waybar otf-font-awesome hyprpaper

sudo pacman -S --noconfirm --needed zsh
hash -r
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
